#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

SetTitleMatchMode, 2
DetectHiddenWindows, On

; --- THIS FILE IS AUTOGENERATED FROM GAMESTRUCT.TXT ---

gameProcess(name) {
	Process, Exist, %name%
	return ErrorLevel
}

winGamePID() {
for proc in ComObjGet("winmgmts:").ExecQuery("Select * from Win32_Process") {
Switch proc.Name {
Case "20XX.exe":
Return gameProcess("20XX.exe")

Case "AI.exe":
Return gameProcess("AI.exe")

Case "Bastion.exe":
Return gameProcess("Bastion.exe")

Case "ShippingPC-BmGame.exe":
Return gameProcess("ShippingPC-BmGame.exe")

Case "BattleBlockTheater.exe":
Return gameProcess("BattleBlockTheater.exe")

Case "Bayonetta.exe":
Return gameProcess("Bayonetta.exe")

Case "isaac-ng.exe":
Return gameProcess("isaac-ng.exe")

Case "BioshockHD.exe":
Return gameProcess("BioshockHD.exe")

Case "Bioshock2HD.exe":
Return gameProcess("Bioshock2HD.exe")

Case "BioshockInfinite.exe":
Return gameProcess("BioshockInfinite.exe")

Case "Borderlands2.exe":
Return gameProcess("Borderlands2.exe")

Case "braid.exe":
Return gameProcess("braid.exe")

Case "BurnoutParadise.exe":
Return gameProcess("BurnoutParadise.exe")

Case "castle.exe":
Return gameProcess("castle.exe")

Case "Celeste.exe":
Return gameProcess("Celeste.exe")

Case "Clone Hero.exe":
Return gameProcess("Clone Hero.exe")

Case "Clustertruck.exe":
Return gameProcess("Clustertruck.exe")

Case "Cuphead.exe":
Return gameProcess("Cuphead.exe")

Case "DARKSOULS.exe":
Return gameProcess("DARKSOULS.exe")

Case "DarkSoulsII.exe":
Return gameProcess("DarkSoulsII.exe")

Case "DarkSoulsIII.exe":
Return gameProcess("DarkSoulsIII.exe")

Case "deadcells.exe":
Return gameProcess("deadcells.exe")

Case "Dishonored.exe":
Return gameProcess("Dishonored.exe")

Case "Dishonored2.exe":
Return gameProcess("Dishonored2.exe")

Case "DOOMx64.exe":
Return gameProcess("DOOMx64.exe")

Case "RED-Win64-Shipping.exe":
Return gameProcess("RED-Win64-Shipping.exe")

Case "DuckGame.exe":
Return gameProcess("DuckGame.exe")

Case "SkyrimSE.exe":
Return gameProcess("SkyrimSE.exe")

Case "TheEndIsNigh.exe":
Return gameProcess("TheEndIsNigh.exe")

Case "Fallout3.exe":
Return gameProcess("Fallout3.exe")

Case "FalloutNV.exe":
Return gameProcess("FalloutNV.exe")

Case "Fallout4.exe":
Return gameProcess("Fallout4.exe")

Case "ffxv_s.exe":
Return gameProcess("ffxv_s.exe")

Case "FortniteClient-Win64-Shipping.exe":
Return gameProcess("FortniteClient-Win64-Shipping.exe")

Case "Furi.exe":
Return gameProcess("Furi.exe")

Case "Gang Beasts.exe":
Return gameProcess("Gang Beasts.exe")

Case "gta3.exe":
Return gameProcess("gta3.exe")

Case "gta-vc.exe":
Return gameProcess("gta-vc.exe")

Case "gta-sa.exe":
Return gameProcess("gta-sa.exe")

Case "GTAIV.exe":
Return gameProcess("GTAIV.exe")

Case "EFLC.exe":
Return gameProcess("EFLC.exe")

Case "GTA5.exe":
Return gameProcess("GTA5.exe")

Case "GuiltyGearXrd.exe":
Return gameProcess("GuiltyGearXrd.exe")

Case "bms.exe":
Return gameProcess("bms.exe")

Case "hl2.exe":
Return gameProcess("hl2.exe")

Case "eldorado.exe":
Return gameProcess("eldorado.exe")

Case "HatinTimeGame.exe":
Return gameProcess("HatinTimeGame.exe")

Case "HITMAN.exe":
Return gameProcess("HITMAN.exe")

Case "hollow_knight.exe":
Return gameProcess("hollow_knight.exe")

Case "INSIDE.exe":
Return gameProcess("INSIDE.exe")

Case "JustCause3.exe":
Return gameProcess("JustCause3.exe")

Case "KingOfFighters98UM.exe":
Return gameProcess("KingOfFighters98UM.exe")

Case "KingOfFighters2002UM_x64.exe":
Return gameProcess("KingOfFighters2002UM_x64.exe")

Case "left4dead2.exe":
Return gameProcess("left4dead2.exe")

Case "LEGOStarWarsSaga.exe":
Return gameProcess("LEGOStarWarsSaga.exe")

Case "limbo.exe":
Return gameProcess("limbo.exe")

Case "MadMax.exe":
Return gameProcess("MadMax.exe")

Case "game.exe":
Return gameProcess("game.exe")

Case "mgsvtpp.exe":
Return gameProcess("mgsvtpp.exe")

Case "ShadowOfMordor.exe":
Return gameProcess("ShadowOfMordor.exe")

Case "MirrorsEdge.exe":
Return gameProcess("MirrorsEdge.exe")

Case "MonsterHunterWorld.exe":
Return gameProcess("MonsterHunterWorld.exe")

Case "MK10.exe":
Return gameProcess("MK10.exe")

Case "MountYourFriends.exe":
Return gameProcess("MountYourFriends.exe")

Case "NSUNS4.exe":
Return gameProcess("NSUNS4.exe")

Case "NFS11.exe":
Return gameProcess("NFS11.exe")

Case "Nidhogg.exe":
Return gameProcess("Nidhogg.exe")

Case "NieRAutomata.exe":
Return gameProcess("NieRAutomata.exe")

Case "Madden19.exe":
Return gameProcess("Madden19.exe")

Case "NBA2K19.exe":
Return gameProcess("NBA2K19.exe")

Case "NNT.exe":
Return gameProcess("NNT.exe")

Case "oriDE.exe":
Return gameProcess("oriDE.exe")

Case "portal2.exe":
Return gameProcess("portal2.exe")

Case "Psychonauts.exe":
Return gameProcess("Psychonauts.exe")

Case "bio4.exe":
Return gameProcess("bio4.exe")

Case "re7.exe":
Return gameProcess("re7.exe")

Case "ROTTR.exe":
Return gameProcess("ROTTR.exe")

Case "RivalsofAether.exe":
Return gameProcess("RivalsofAether.exe")

Case "RocketLeague.exe":
Return gameProcess("RocketLeague.exe")

Case "SaintsRowIV.exe":
Return gameProcess("SaintsRowIV.exe")

Case "ShovelKnight.exe":
Return gameProcess("ShovelKnight.exe")

Case "SkullGirls.exe":
Return gameProcess("SkullGirls.exe")

Case "SonicMania.exe":
Return gameProcess("SonicMania.exe")

Case "Spelunky.exe":
Return gameProcess("Spelunky.exe")

Case "Starwhal.exe":
Return gameProcess("Starwhal.exe")

Case "StriderX64_r.exe":
Return gameProcess("StriderX64_r.exe")

Case "SuperMeatBoy.exe":
Return gameProcess("SuperMeatBoy.exe")

Case "SH.exe":
Return gameProcess("SH.exe")

Case "TekkenGame-Win64-Shipping.exe":
Return gameProcess("TekkenGame-Win64-Shipping.exe")

Case "Transistor.exe":
Return gameProcess("Transistor.exe")

Case "SSFIV.exe":
Return gameProcess("SSFIV.exe")

Case "VVVVVV.exe":
Return gameProcess("VVVVVV.exe")

Case "witcher3.exe":
Return gameProcess("witcher3.exe")

Case "WolfNewOrder_x64.exe":
Return gameProcess("WolfNewOrder_x64.exe")

Case "Yakuza0.exe":
Return gameProcess("Yakuza0.exe")

Case "sdhdship.exe":
Return gameProcess("sdhdship.exe")

Case "Overwatch.exe":
Return gameProcess("Overwatch.exe")

Case "bf1.exe":
Return gameProcess("bf1.exe")

Case "payday2_win32_release.exe":
Return gameProcess("payday2_win32_release.exe")

Case "CMW.exe":
Return gameProcess("CMW.exe")

Case "METAL GEAR RISING REVENGEANCE.exe":
Return gameProcess("METAL GEAR RISING REVENGEANCE.exe")

Case "bhd.exe":
Return gameProcess("bhd.exe")

Case "Broforce-798.exe":
Return gameProcess("Broforce-798.exe")

Case "HotlineMiami2.exe":
Return gameProcess("HotlineMiami2.exe")

Case "TheMessenger.exe":
Return gameProcess("TheMessenger.exe")

Case "Ninja.exe":
Return gameProcess("Ninja.exe")

Case "This War of Mine.exe":
Return gameProcess("This War of Mine.exe")

Case "Wreckfest_x64.exe":
Return gameProcess("Wreckfest_x64.exe")

Case "dontstarve_steam.exe":
Return gameProcess("dontstarve_steam.exe")

Case "IamBread.exe":
Return gameProcess("IamBread.exe")

Case "WizardOfLegend.exe":
Return gameProcess("WizardOfLegend.exe")

Case "SnakePass-Win64-Shipping.exe":
Return gameProcess("SnakePass-Win64-Shipping.exe")

Case "Overcooked2.exe":
Return gameProcess("Overcooked2.exe")

Case "DevilMayCry5.exe":
Return gameProcess("DevilMayCry5.exe")

Case "EtG.exe":
Return gameProcess("EtG.exe")

Case "SoulcaliburVI.exe":
Return gameProcess("SoulcaliburVI.exe")

Case "re2.exe":
Return gameProcess("re2.exe")

Case "HotlineGL.exe":
Return gameProcess("HotlineGL.exe")

Case "ApeOut.exe":
Return gameProcess("ApeOut.exe")

Case "Katana ZERO.exe":
Return gameProcess("Katana ZERO.exe")

Case "Baba Is You.exe":
Return gameProcess("Baba Is You.exe")

Case "drt.exe":
Return gameProcess("drt.exe")

Case "Rayman Origins.exe":
Return gameProcess("Rayman Origins.exe")

Case "CrashBandicootNSaneTrilogy.exe":
Return gameProcess("CrashBandicootNSaneTrilogy.exe")

Case "Spyro-Win64-Shipping.exe":
Return gameProcess("Spyro-Win64-Shipping.exe")

Case "srb2kart.exe":
Return gameProcess("srb2kart.exe")

Case "HorizonChase.exe":
Return gameProcess("HorizonChase.exe")

Case "YLILWin64.exe":
Return gameProcess("YLILWin64.exe")

Case "AM2R.exe":
Return gameProcess("AM2R.exe")

Case "Sonic3AIR.exe":
Return gameProcess("Sonic3AIR.exe")

Case "SpeedRunners.exe":
Return gameProcess("SpeedRunners.exe")

Case "SonicGenerations.exe":
Return gameProcess("SonicGenerations.exe")

Case "I Wanna Be The Boshy.exe":
Return gameProcess("I Wanna Be The Boshy.exe")

Case "cannonball.exe":
Return gameProcess("cannonball.exe")

Case "DOOM64.exe":
Return gameProcess("DOOM64.exe")

Case "gzdoom.exe":
Return gameProcess("gzdoom.exe")

Case "TombRaider.exe":
Return gameProcess("TombRaider.exe")

Case "umvc3.exe":
Return gameProcess("umvc3.exe")

Case "AWayOut.exe":
Return gameProcess("AWayOut.exe")

Case "BurnoutPR.exe":
Return gameProcess("BurnoutPR.exe")

Case "Worms W.M.D.exe":
Return gameProcess("Worms W.M.D.exe")

Case "mbacPC.exe":
Return gameProcess("mbacPC.exe")

Case "sw.x64.exe":
Return gameProcess("sw.x64.exe")

Case "MassEffect.exe":
Return gameProcess("MassEffect.exe")

Case "MassEffect2.exe":
Return gameProcess("MassEffect2.exe")

Case "SaintsRowTheThird_DX11.exe":
Return gameProcess("SaintsRowTheThird_DX11.exe")

Case "wargroove64.exe":
Return gameProcess("wargroove64.exe")

Case "forza_x64_release_final.exe":
Return gameProcess("forza_x64_release_final.exe")

Case "soniccd.exe":
Return gameProcess("soniccd.exe")

Case "Golf With Your Friends.exe":
Return gameProcess("Golf With Your Friends.exe")

Case "BatmanAC.exe":
Return gameProcess("BatmanAC.exe")

Case "Injustice.exe":
Return gameProcess("Injustice.exe")

Case "CaveStory+.exe":
Return gameProcess("CaveStory+.exe")

Case "HyperLightDrifter.exe":
Return gameProcess("HyperLightDrifter.exe")

Case "Outward.exe":
Return gameProcess("Outward.exe")

Case "KillerInstinctX64_r.exe":
Return gameProcess("KillerInstinctX64_r.exe")

Case "Timespinner.exe":
Return gameProcess("Timespinner.exe")

Case "SHMCD.exe":
Return gameProcess("SHMCD.exe")

Case "Final Fight LNS Ultimate.exe":
Return gameProcess("Final Fight LNS Ultimate.exe")

Case "Oblivion.exe":
Return gameProcess("Oblivion.exe")

Case "openmw.exe":
Return gameProcess("openmw.exe")

Case "SorR.exe":
Return gameProcess("SorR.exe")

Case "Spel2.exe":
Return gameProcess("Spel2.exe")

Case "LEGOLCUR_DX11.exe":
Return gameProcess("LEGOLCUR_DX11.exe")

Case "sm64.exe":
Return gameProcess("sm64.exe")

Case "Rayman Redemption.exe":
Return gameProcess("Rayman Redemption.exe")

Case "LittleNightmares.exe":
Return gameProcess("LittleNightmares.exe")

Case "GGXXACPR_Win.exe":
Return gameProcess("GGXXACPR_Win.exe")

Case "BloodstainedRotN-Win64-Shipping.exe":
Return gameProcess("BloodstainedRotN-Win64-Shipping.exe")

Case "sonic.exe":
Return gameProcess("sonic.exe")

Case "sonic2app.exe":
Return gameProcess("sonic2app.exe")

Case "OR2006C2C.EXE":
Return gameProcess("OR2006C2C.EXE")

Case "Rayman Legends.exe":
Return gameProcess("Rayman Legends.exe")

Case "sh2pc.exe":
Return gameProcess("sh2pc.exe")

Case "sunset.exe":
Return gameProcess("sunset.exe")

Case "MaxPayne3.exe":
Return gameProcess("MaxPayne3.exe")

Case "My Friend Pedro - Blood Bullets Bananas.exe":
Return gameProcess("My Friend Pedro - Blood Bullets Bananas.exe")

Case "Stardew Valley.exe":
Return gameProcess("Stardew Valley.exe")

Case "FEZ.exe":
Return gameProcess("FEZ.exe")

Case "Hades.exe":
Return gameProcess("Hades.exe")

Case "HotshotRacing.exe":
Return gameProcess("HotshotRacing.exe")

Case "WHAT THE GOLF.exe":
Return gameProcess("WHAT THE GOLF.exe")

Case "oriwotw.exe":
Return gameProcess("oriwotw.exe")

Case "MBAA.exe":
Return gameProcess("MBAA.exe")

Case "Simpsons.exe":
Return gameProcess("Simpsons.exe")

Case "Bully.exe":
Return gameProcess("Bully.exe")

Case "MaxPayne.exe":
Return gameProcess("MaxPayne.exe")

Case "maxpayne2.exe":
Return gameProcess("maxpayne2.exe")

Case "AssassinsCreedIIGame.exe":
Return gameProcess("AssassinsCreedIIGame.exe")

Case "ACBSP.exe":
Return gameProcess("ACBSP.exe")

Case "Viva Pinata.exe":
Return gameProcess("Viva Pinata.exe")

Case "witcher2.exe":
Return gameProcess("witcher2.exe")

Case "AC4BFSP.exe":
Return gameProcess("AC4BFSP.exe")

Case "spearmint_x86_64.exe":
Return gameProcess("spearmint_x86_64.exe")

Case "FOER.exe":
Return gameProcess("FOER.exe")

Case "WOGR.exe":
Return gameProcess("WOGR.exe")

Case "KINGDOM HEARTS HD 1.5+2.5 ReMIX.exe":
Return gameProcess("KINGDOM HEARTS HD 1.5+2.5 ReMIX.exe")

Case "KINGDOM HEARTS HD 2.8 Final Chapter Prologue.exe":
Return gameProcess("KINGDOM HEARTS HD 2.8 Final Chapter Prologue.exe")

Case "KINGDOM HEARTS III.exe":
Return gameProcess("KINGDOM HEARTS III.exe")

Case "Fable Anniversary.exe":
Return gameProcess("Fable Anniversary.exe")

Case "FF7.exe":
Return gameProcess("FF7.exe")

Case "Shenmue.exe":
Return gameProcess("Shenmue.exe")

Case "Shenmue2.exe":
Return gameProcess("Shenmue2.exe")

Case "Tsonic_win.exe":
Return gameProcess("Tsonic_win.exe")

} ; WINGAME
}
	
Return 0
}

emulatorPID() {
for proc in ComObjGet("winmgmts:").ExecQuery("Select * from Win32_Process") {
Switch proc.Name {
Case "retroarch.exe":
Return gameProcess("retroarch.exe")

Case "Project64.exe":
Return gameProcess("Project64.exe")

Case "Dolphin.exe":
Return gameProcess("Dolphin.exe")

Case "Cemu.exe":
Return gameProcess("Cemu.exe")

Case "DeSmuMe.exe":
Return gameProcess("DeSmuMe.exe")

Case "citra-qt.exe":
Return gameProcess("citra-qt.exe")

Case "demul.exe":
Return gameProcess("demul.exe")

Case "PCSX2.exe":
Return gameProcess("PCSX2.exe")

Case "PPSSPPWindows64.exe":
Return gameProcess("PPSSPPWindows64.exe")

Case "redream.exe":
Return gameProcess("redream.exe")

Case "mupen64plus-gui.exe":
Return gameProcess("mupen64plus-gui.exe")

Case "rpcs3.exe":
Return gameProcess("rpcs3.exe")

Case "yuzu.exe":
Return gameProcess("yuzu.exe")

Case "xenia_canary.exe":
Return gameProcess("xenia_canary.exe")

Case "xenia.exe":
Return gameProcess("xenia.exe")

Case "Ryujinx.exe":
Return gameProcess("Ryujinx.exe")

} ; EMUGAME
}
	
Return 0
}

gamePID() {

	Exist := emulatorPID()
	
	If (Exist = 0) {
		Exist := winGamePID()
	}
	
	Return Exist
}